[project]
name = "sella-demo"
version = "0.1.0"
description = "Add a short description here"
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"
pip = ">=24.0,<25"
jupyter = ">=1.0.0,<1.1"
ase = ">=3.23.0,<3.24"
tblite = ">=0.3.0,<0.4"
tblite-python = ">=0.3.0,<0.4"
jax = ">=0.4.27,<0.5"
jaxlib = ">=0.4.23,<0.5"
